spring:
  application:
    name: bookstore-backend

  datasource:
    url: jdbc:mysql://localhost:3306/bookstore_database
    username: root
    password: Pass@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
jwt:
  secret: mySecretKeyForBookStoreApplicationJwtTokenGeneration123456789
  expiration: 86400000
server:
  port: 8082

